### ISSUE TITLE
No mention of perl in install instructions?

### ISSUE THREAD

**Issue by bcomnes** [LaTeXing/LaTeXing-Documentation#2]
Interest in working on LaTeX in a windows environment has brought me to your package, however I am more familiar with unix environments (Linux and OSX).  Running the check system, it shows that perl is a requirement.  

The introduction, however, makes no mention if installing perl on windows, other than the order of operations in relation to MikTex.  It should probably be mentioned since perl isn't included in windows like it is on most unix systems.

Also, there are a few distributions of perl on windows.  Which ones do you recommend?

**Comment by csch0** [comment]
Strawberry perl is a good option on windows.
